from . import payment_provider
from . import payment_transaction
from . import pos_payment_method
from . import res_partner
from . import vipps_api_client
from . import vipps_data_management
from . import vipps_profile_wizard
from . import vipps_onboarding_wizard
from . import vipps_security
from . import vipps_webhook_security
from . import vipps_data_retention